import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';

const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       <div className="grid min-h-screen place-content-center bg-blue-950 px-4">
        <div className="sm:w-[500px] md:w-[600px] lg:w-[700px]">
          <Navbar />
          {children}
        </div>
       </div>
      </body>
    </html>
  );
}
