import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';

const space_Grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_Grotesk.className}>
       <div className="grid  place-content-center min-h-screen bg-gray-500">
        <div className="sm:w-[500px] md:w-[600px] lg:w-[700px]">
          <Navbar />
          {children}
        </div>
       </div>
      </body>
    </html>
  );
}
